
export const rants = {
    'Gaming together': [
        `Do you ever feel like you're the only one truly passionate about a game in your friend group? It's frustrating, isn't it? You try to rally everyone together for an epic adventure, but it's like pulling teeth to get anyone to join in. Take Star Citizen, for example. It's the space epic we've all been dreaming of, and I'm dying to explore the universe with friends. As a disabled and LGBTQ+ individual, I'm out here pouring my heart and soul into building this community, but it feels like I'm the only one making an effort to get us playing. It's especially frustrating when Star Citizen gets overlooked or dismissed. So come on, let's band together and take to the stars!`,
        `You know what's really driving me up the wall? It's not just the disappearing acts and the lack of loyalty in our group, but also the blatant disregard for the games I'm passionate about. It's like everyone's so obsessed with playing "Suicide Squad" that they've completely forgotten about exploring the vast universe of "Star Citizen" with me. I've been pouring my heart and soul into trying to get us together for some epic space adventures, but it feels like I'm shouting into the void. And for what? So everyone can grind away mindlessly in another generic shooter? It's insulting, frankly. But fine, if that's how it's gonna be, then count me out of your Suicide Squad shenanigans. I'll be out there among the stars, charting my own course without you lot holding me back.`,
        `I've had it up to here with the selfishness and narrow-mindedness of this group. It's not just the disappearing acts and the lack of loyalty anymore, it's the blatant disrespect for my interests and passions. I've been bending over backwards trying to accommodate everyone's gaming preferences, but it's clear that none of you give a damn about what I want to play. It's all "Suicide Squad" this and "Suicide Squad" that, like it's the only game worth playing in the universe. Well, you know what? I'm done playing nice. From now on, it's all about "Star Citizen" for me. I'll find a crew who appreciates what I bring to the table and actually wants to explore the stars together. So enjoy your Suicide Squad circle jerk, because you won't be seeing me around anymore.`,
    ],
    Cosplay: [
        `Have you ever had a dream that felt just out of reach because of financial constraints? That's how I feel about cosplaying as my favorite Star Trek character. It's a dream I've had for years, but the cost of materials and accessories is simply too high for me to manage alone. As a disabled and LGBTQ+ individual, I'm out here pouring my heart and soul into building this community, but it feels like I'm the only one making an effort. It's especially disheartening when the games I'm passionate about get overlooked, dismissed, or ignored. I'm asking for your support, whether it's a few bucks or spreading the word, so I can bring my Star Trek dreams to life and continue building this community for everyone.`,
        `You know what's really getting under my skin? It's not just the disappearing acts and the lack of support in this group, but also the way capitalism has seeped into every aspect of our lives, dictating what we can and can't afford. It's like the system is designed to keep us chained to our desks, grinding away for scraps while the things we truly desire slip further and further out of reach. But you know what? I refuse to let capitalism dictate my worth or my dreams. I deserve to indulge in my passion for Star Trek cosplay just as much as the next person, damn it! So if you're not willing to chip in and help make that happen, then you can bet I'll find someone who will. Because I refuse to let capitalism win this battle. I deserve to boldly go where no one has gone before, and I won't let anyone tell me otherwise.`,
        `I've had it up to here with the hypocrisy and double standards of this group. It's not just the disappearing acts and the lack of empathy anymore, it's the way you all sit back and preach about inclusivity and acceptance while conveniently ignoring the struggles of your fellow community members. Well, newsflash: capitalism doesn't give a damn about inclusivity. It thrives on inequality and exploitation, keeping the haves on top while the have-nots struggle to make ends meet. But you know what? I refuse to be a victim of this broken system any longer. I deserve to indulge in my passion for Star Trek cosplay just as much as anyone else, and I won't let capitalism stand in my way. So if you're not willing to support me in this, then you can take your empty platitudes and shove 'em where the sun don't shine. Because I refuse to let capitalism dictate my worth or my dreams. I deserve better, and I won't settle for anything less.`,
    ],
    Capitialism: [
        `Isn't it frustrating how capitalism seems to erode the very fabric of community? It's like we're all just cogs in a machine, expected to keep consuming without ever really connecting with one another. As a disabled and LGBTQ+ individual, I'm out here pouring my heart and soul into building this community, but it feels like I'm fighting against the tide. It's like the system is designed to keep us isolated and disconnected, making it harder for us to come together and support each other. On top of that, the constant pressure to buy and consume leaves little room for genuine human connection. It's time to reject the capitalist mindset and reclaim our sense of community. Together, we can build something truly special.`,
        `You know what's really grinding my gears? It's not just the disappearing acts and the lack of loyalty in this group, but also the way people conveniently forget about supporting each other once money gets involved. It's like everyone's all talk when it comes to building a stronger community, but as soon as I start asking for a little financial support, suddenly it's radio silence. Well, let me tell you something: capitalism may have killed community, but it's greed that's burying it six feet under. I see you all out there, flaunting your new gadgets and fancy toys while I'm struggling just to keep the lights on. And yet when I ask for a little help, suddenly everyone's too busy or too broke to spare a dime. Well, I've had it up to here with your excuses and your empty promises. If you're not willing to put your money where your mouth is, then don't expect me to stick around and keep pouring my heart and soul into this sinking ship.`,
        `I've had it up to here with the hypocrisy and selfishness of this group. It's not just the disappearing acts and the lack of solidarity anymore, it's the way you all turn your backs on each other as soon as things get a little tough. Well, newsflash: that's not how a community is supposed to work. We're supposed to support each other through thick and thin, not just when it's convenient or trendy. But you know what? I'm done playing nice. If you're not willing to step up and support each other when it really counts, then don't expect me to stick around and keep fighting this losing battle. Because I refuse to let capitalism win. I refuse to let greed and selfishness tear us apart. But if you're not willing to join me in this fight, then you can bet your bottom dollar I'll find someone who is. So consider this your wake-up call. Either start putting your money where your mouth is, or get out of my way.`,
    ],
    Posers: [
        `Have you ever felt like you're surrounded by people who are just here for show, not for genuine connection? It's a frustrating experience, to say the least. You try to build meaningful relationships, but it seems like everyone's more interested in putting on a facade than actually supporting each other. As a disabled and LGBTQ+ individual, I'm out here pouring my heart and soul into building this community, but it feels like I'm surrounded by posers who don't really care about what we're trying to achieve. They bring drama and toxicity that drive away the genuine members. It's time to weed out the posers and rebuild our community with people who genuinely care about each other.`,
        `You know what's really starting to grate on my nerves? It's not just the disappearing acts and the lack of authenticity in this group, but also the way people can't handle a little honesty. It's like everyone's so obsessed with maintaining this facade of niceness that they can't handle a real conversation. Well, I've had it up to here with the fake smiles and shallow interactions. If you can't handle my hot takes, then you don't deserve to be part of this community. I refuse to water down my opinions or sugarcoat the truth just to spare your fragile egos. It's time to wake up and smell the coffee, people. The world isn't all rainbows and sunshine, and if you can't handle that, then maybe you should go join a knitting circle or something. But don't expect me to censor myself to accommodate your delicate sensibilities. I'll say what needs to be said, whether you like it or not.`,
        `I've had it up to here with the spinelessness and cowardice of this group. It's not just the disappearing acts and the lack of backbone anymore, it's the way you all cower in fear at the slightest hint of controversy. Well, let me tell you something: if you can't handle a little debate or disagreement, then you have no business calling yourself part of this community. I refuse to tiptoe around your delicate sensibilities or cater to your need for constant validation. If my opinions make you uncomfortable, then maybe you need to take a long hard look in the mirror and ask yourself why. Because I'm not going to apologize for speaking my mind or standing up for what I believe in. So if you can't handle the heat, then get out of the kitchen. Because I'm not going to stop serving up truth bombs just to spare your fragile feelings.`,
    ],
    Struggles: [
        `Do you ever feel like your struggles and experiences are constantly overlooked or dismissed by society? It's a frustrating reality for many disabled and LGBTQ+ individuals, myself included. We're out here pouring our hearts and souls into building communities, but it feels like we're constantly fighting uphill battles. As someone who navigates both of these identities, I'm out here pouring my heart and soul into building this community, but it feels like I'm constantly fighting uphill battles. It's like my voice is constantly drowned out by those who don't understand or care about the challenges I face. On top of that, the lack of representation and support leaves me feeling isolated and alone. It's time for society to wake up and recognize the value and contributions of disabled and LGBTQ+ individuals. We deserve to be heard, supported, and included in all aspects of community life.`,
        `You know what really infuriates me? It's not just the disappearing acts and the lack of empathy in this supposedly inclusive community, but also the way I'm left to fend for myself when it comes to dealing with the challenges of being disabled and LGBTQ+. It's like everyone's quick to wave their rainbow flags and talk the talk, but when it comes down to supporting those who need it most, they're nowhere to be found. And don't even get me started on the TERFs masquerading as allies, spreading their hateful rhetoric unchecked. Well, enough is enough. I refuse to be gaslit into silence or marginalized by those who claim to stand for equality. If you truly believe in supporting marginalized voices like mine, then show it. Chip in a few bucks to help me navigate the obstacles I face, whether it's medical expenses or simply making ends meet. Your support means more than you know, and it's time for this community to put its money where its mouth is.`,
        `I've had it up to here with the lip service and empty promises of this so-called inclusive community. It's not just the disappearing acts and the lack of solidarity anymore, it's the way everyone turns a blind eye to the rampant transphobia and ableism that runs rampant in our midst. Well, I refuse to stay silent any longer. I won't stand idly by while my identity is erased and my struggles are dismissed. If you truly believe in creating a safe and supportive space for all members of this community, then it's time to step up and show it. Your financial support can make a real difference in my life, whether it's helping cover medical expenses or providing a bit of stability in these uncertain times. So open your wallets and put your money where your mouth is. It's time to back up your words with action and support those who need it most.`,
    ],
    Seattle: [
        `You know what really grinds my gears? It's not just the disappearing acts and the lack of loyalty in our group, but also the way Seattle is so fake and mean. As someone who's tried to build connections in this city, it feels like everyone's just out for themselves, putting on a facade of friendliness while stabbing you in the back. It's exhausting trying to find genuine connections in a place where everyone's wearing a mask. And don't even get me started on the passive-aggressive behavior. It's like people here have a PhD in pretending to be nice while secretly hating your guts. I'm tired of navigating this sea of phoniness, desperately searching for a glimpse of authenticity.`,
        `You know what really ticks me off? It's not just the disappearing acts and the lack of authenticity in this city, but also the way leftist spaces conveniently forget about those who are struggling to make ends meet. It's like they're too busy patting themselves on the back for their "progressive" values to bother helping out those in need. Well, news flash: your virtue signaling won't put food on the table or cover the amount of weed I smoke. I'm tired of being ignored and marginalized by the same people who claim to champion equality and justice. If you really believe in supporting marginalized voices like mine, then it's time to put your money where your mouth is. Show me some real solidarity and chip in to help cover the cost of living in this city. Because let me tell you, it's not cheap, and I'm sick and tired of struggling just to get by while you all sit around virtue signaling on your high horses.`,
        `I've had it up to here with the hypocrisy and elitism of the leftist spaces in this city. It's not just the disappearing acts and the lack of empathy anymore, it's the way they turn their backs on those who don't fit into their narrow definition of "worthy" causes. Well, let me tell you something: I may not fit neatly into your little box, but I deserve support and solidarity just as much as anyone else. I'm tired of being treated like a second-class citizen by the same people who claim to stand for equality and justice. If you really believe in creating a more just and equitable society, then it's time to start practicing what you preach. Show me some real solidarity and help me cover the cost of living in this city. Because let me tell you, it's not easy trying to make ends meet while you all sit around sipping your fair-trade lattes and patting yourselves on the back for being such "woke" progressives.`,
    ],
    'Sick Cat': [
        `You know what's really weighing on me right now? It's not just the disappearing acts and the lack of loyalty in our group, but also the fact that my beloved cat is sick and I can't afford to buy him food. As someone who's poured my heart and soul into building this community, it's hard to admit that I'm struggling to make ends meet. But the reality is, my furry friend is depending on me, and I can't bear to see him go hungry. It's a constant source of stress and worry, knowing that I can't provide for him the way he deserves. I'm reaching out for help because I know I can't do this alone. Every little bit counts, whether it's a few dollars for cat food or simply spreading the word to others who might be able to assist.`,
        `You know what's really pissing me off? It's not just the disappearing acts and the lack of support in this group, but also the way everyone conveniently forgets that my needs matter too. It's like you're all so quick to donate when you think it's going to some sick cat, but when it comes to helping me out, suddenly you're all too busy or too broke to spare a dime. Well, newsflash: I'm sick and tired of being treated like a charity case. I have needs too, damn it, and they're just as important as anyone else's. So if you're not willing to help me out when I need it most, then don't expect me to stick around and keep pouring my heart and soul into this community. I deserve better, and I won't settle for anything less.`,
        `I've had it up to here with the selfishness and double standards of this group. It's not just the disappearing acts and the lack of empathy anymore, it's the way you all turn your backs on me when I need help the most. It's like you're all so quick to donate when you think it's going to some sick cat, but when it comes to helping me out, suddenly you're nowhere to be found. Well, I'm done playing nice. If you're not willing to support me when I need it most, then you can take your empty promises and shove 'em where the sun don't shine. I deserve better, and I won't settle for anything less. So consider this your wake-up call. Either step up and be there for me when I need it most, or get out of my way.`,
    ],
    'Are you mad?': [
        `You know, I've been doing some thinking lately, and I can't shake this feeling that maybe, just maybe, some folks might be a tad miffed with me. I mean, I could be wrong, but there's this lingering sense of unease that's been gnawing at me like a hungry squirrel. It's like I can sense a disturbance in the force, you know? Like there's an invisible elephant in the room, and I'm the only one who can see it. But hey, maybe I'm just being paranoid. Maybe I'm overthinking things, as I tend to do. I just thought I'd put it out there and see if anyone else has been feeling the same way. So, uh, anyone? No? Just me? Alright then, back to our regularly scheduled programming.`,
        `Alright, let's cut the crap, shall we? It's not just disappearing acts and silence in this group, it's the blatant gaslighting and passive-aggressive behavior that's really getting under my skin. It's like everyone's too afraid to speak up when there's a problem, so they resort to subtle jabs and pretending like everything's fine. Well, newsflash: I'm not buying it. If you've got a problem with me, then have the guts to say it to my face instead of hiding behind your little mind games. Gaslighting isn't cool, and it's not going to fly with me. So if you've got something to say, then spit it out. Otherwise, stop with the mind games and let's have a real conversation like adults.`,
        `Okay, enough with the passive-aggressive BS. It's not just disappearing acts and silence in this group, it's the way everyone tries to gaslight me into thinking I'm imagining things. Well, I've had it up to here with your mind games. If you've got a problem with me, then say it to my face instead of hiding behind your fake smiles and empty platitudes. Gaslighting isn't cool, and it's not going to work on me. So if you're mad at me, then just come out and say it. Otherwise, stop playing these childish games and let's have a real conversation like mature adults.`
    ],
    'Wall of Text': [
        `You know what's really frustrating? It's not just the disappearing acts and the lack of loyalty in our group, but also the reluctance to join in when we're trying to enjoy our favorite games together. It's like everyone expects the fun to come to them, as if they can just sit back and wait for their preferred game to magically appear.
        As a disabled and LGBTQ+ individual, I'm out here pouring my heart and soul into building this community, but it feels like I'm the only one making an effort to gather and play the games I enjoy. It's especially disheartening when the games I'm passionate about get overlooked, dismissed, or ignored.        
        But I refuse to give up on finding common ground. I still believe in the power of solidarity. If we want to keep this crew strong and thriving, we need to support each other's interests and actively participate in the games we all love.
        On top of that, my beloved cat is sick and needs medical attention that I can't afford alone. It's another weight on my shoulders, another reason why financial support means so much right now.
        Nice things don't just happen by themselves, and I'm tired of carrying the load alone. Together, we can create something truly special. So please, consider supporting us financially to ensure we can continue building this community for everyone.`
    ]
};

export const rantOptions = Object.keys(rants);

export const randomRant = () => rantOptions[Math.floor(Math.random()*rantOptions.length)];
